# -*- coding: utf-8 -*-
"""GenAi_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFGbTfJMnrNyqf4HhjR_r8v1dH3kQIMZ
"""

# =========================================
# Prompt Engineering Techniques in Colab
# Zero-shot | Few-shot | CoT | Interview | ToT + LLM demo
# =========================================

# Install libraries (Colab safe)
!pip -q install transformers torch accelerate pandas

import pandas as pd
import torch
from transformers import pipeline
from IPython.display import display

# -----------------------------------------
# Problem
# -----------------------------------------
problem = """
A shopkeeper buys a pen for ₹10 and sells it for ₹15.
He sells 20 pens. What is the profit?
"""

print("\nPROBLEM:\n", problem)


# -----------------------------------------
# Prompting Techniques (Manual reasoning)
# -----------------------------------------

def zero_shot(problem):
    return "Profit per pen = 15 - 10 = 5. Total profit = 5 × 20 = ₹100"


def few_shot(problem):
    examples = """
Example 1:
CP = 20, SP = 30, Quantity = 10
Profit = (30-20)*10 = 100

Example 2:
CP = 50, SP = 70, Quantity = 5
Profit = (70-50)*5 = 100
"""
    answer = "Using pattern: (15-10)*20 = ₹100"
    return examples + "\nAnswer:\n" + answer


def chain_of_thought(problem):
    return """
Step 1: Cost Price = 10
Step 2: Selling Price = 15
Step 3: Profit per pen = 5
Step 4: Total profit = 5 × 20 = ₹100
Final Answer: ₹100
"""


def interview_prompting(problem):
    return """
Q1: Cost price per pen? → 10
Q2: Selling price per pen? → 15
Q3: Profit per pen? → 5
Q4: Profit for 20 pens? → ₹100
"""


def tree_of_thought(problem):
    return """
Approach 1: (15-10) × 20 = 100

Approach 2:
Revenue = 15×20 = 300
Cost = 10×20 = 200
Profit = 300-200 = 100

Conclusion → ₹100
"""


# -----------------------------------------
# Print outputs
# -----------------------------------------

methods_output = {
    "Zero-shot": zero_shot(problem),
    "Few-shot": few_shot(problem),
    "Chain of Thought": chain_of_thought(problem),
    "Interview": interview_prompting(problem),
    "Tree of Thoughts": tree_of_thought(problem),
}

for name, output in methods_output.items():
    print(f"\n{name} Output:\n{output}")


# -----------------------------------------
# Comparison Table
# -----------------------------------------

data = {
    "Method": ["Zero-shot", "Few-shot", "Chain of Thought", "Interview", "Tree of Thoughts"],
    "Reasoning Strength": ["Low", "Medium", "High", "Very High", "Extremely High"],
    "Accuracy": ["Medium", "High", "Very High", "Very High", "Best"],
    "Use Case": [
        "Simple Q&A",
        "Pattern tasks",
        "Math/Logic",
        "Teaching systems",
        "AI Agents"
    ]
}

print("\nComparison Table:")
display(pd.DataFrame(data))


# -----------------------------------------
# LLM Reasoning (FLAN-T5 — better than GPT2)
# -----------------------------------------

print("\nLoading LLM model (first time takes ~30s)...")

generator = pipeline(
    "text2text-generation",
    model="google/flan-t5-base",
    device=0 if torch.cuda.is_available() else -1
)

prompt = "Solve step by step: A pen costs 10, sells 15, sold 20. What is the profit?"

llm_output = generator(prompt, max_new_tokens=80)

print("\nLLM Generated Answer:\n")
print(llm_output[0]["generated_text"])